services:
  web:
    image: nginx:alpine
    container_name: hugo-website
    restart : always
    # ports:
    #   - "8002:80"
    networks:
      - proxy_wan_wan
    labels:
      - traefik.enable=true
      - traefik.http.routers.hugo-rvlab.rule=Host(`${app_url}`)
      - traefik.http.services.hugo-rvlab.loadbalancer.server.port=80
    volumes:
      - ${app_data}/htdocs/public/:/usr/share/nginx/html
      - ${app_data}/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  proxy_wan_wan:
    external: true
