services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${app_domain}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
      - N8N_LOG_LEVEL=info
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - WEBHOOK_URL=https://${webhook_domain}/
      - GENERIC_TIMEZONE=${timezone}
    labels:
      - traefik.enable=true
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      # Router for webhook_domain
      - traefik.http.routers.n8n-webhook.entrypoints=https-external
      - traefik.http.routers.n8n-webhook.rule=Host(`${webhook_domain}`)
      - traefik.http.routers.n8n-webhook.service=n8n
      # Router for app_domain
      - traefik.http.routers.n8n-app.entrypoints=https-internal
      - traefik.http.routers.n8n-app.rule=Host(`${app_domain}`)
      - traefik.http.routers.n8n-app.service=n8n
    volumes:
      - ${app_data_path}:/home/node/.n8n
    networks:
      - proxy
networks:
  proxy:
    external: true
