services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=${app_url}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
      - N8N_LOG_LEVEL=info
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - WEBHOOK_URL=https://${webhook_domain}/
      - GENERIC_TIMEZONE=${timezone}
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n-http.entrypoints=web
      - traefik.http.routers.n8n-http.rule=Host(`${app_url}`) || Host(`${webhook_domain}`)
      - traefik.http.routers.n8n-https.entrypoints=websecure
      - traefik.http.routers.n8n-https.rule=Host(`${app_url}`) || Host(`${webhook_domain}`)
      - traefik.http.routers.n8n-https.tls=true
    volumes:
      - ${app_data}:/home/node/.n8n
    networks:
      - front
networks:
  front:
    external: true
