services:

  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    hostname: it-tools
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.it-tools.rule=Host(`tools.rvlab.xyz`)
      - traefik.http.services.it-tools.loadbalancer.server.port=80
      #- traefik.http.routers.it-tools.middlewares=restriction@file

networks:
 proxy:
   external: true