services:

  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    hostname: it-tools
    restart: unless-stopped
    # ports:
    #   - 8080:80
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.it-tools.entrypoints=https-internal
      - traefik.http.routers.it-tools.rule=Host(`${app_domain}`)
      - traefik.http.services.it-tools.loadbalancer.server.port=80
networks:
 proxy:
   external: true