services:
  vaultwarden:
    restart: always
    container_name: vaultwarden
    image: vaultwarden/server:latest-alpine
    volumes:
      - ${app_data_path}/data:/data/
      - ${app_data_path}/logs:/data/logs
    labels:
      - traefik.enable=true
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - traefik.http.routers.vaultwarden.rule=Host(`${app_domain}`)
      - traefik.http.routers.vaultwarden.entrypoints=https-external
      # Admin Route with IP Restriction
      - traefik.http.routers.vaultwarden-admin.rule=Host(`${app_domain}`) && PathPrefix(`/admin`)
      - traefik.http.routers.vaultwarden-admin.entrypoints=https-internal
      # API Version Endpoint with IP Restriction
      - traefik.http.routers.vaultwarden-api.rule=Host(`${app_domain}`) && PathPrefix(`/api/version`)
      - traefik.http.routers.vaultwarden-api.entrypoints=https-internal
    networks:
      - proxy
      - internal
    environment:
      - TZ=${timezone}
      - SMTP_HOST=${mail_host}
      - SMTP_FROM=${mail_username}
      - SMTP_FROM_NAME=VaultWarden
      - SMTP_SECURITY=starttls
      - SMTP_PORT=${mail_port}
      - SMTP_USERNAME=${mail_username}
      - SMTP_PASSWORD=${mail_password}
      - SMTP_TIMEOUT=30
      - SMTP_AUTH_MECHANISM="Plain"
      - LOGIN_RATELIMIT_MAX_BURST=5
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=https://${app_domain}
      - INVITATION_ORG_NAME=RivenVault
      - INVITATIONS_ALLOWED=false
      - ADMIN_TOKEN=${admin_token}
      - ROCKET_ENV=prod
      - LOG_LEVEL=error
      - LOG_FILE=/data/logs/access.log
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=6
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLED=true

  vaultwarden-backup:
    image: bruceforce/vaultwarden-backup:latest
    container_name: vaultwarden-backup
    hostname: vaultwarden-backup
    restart: always
    init: true
    depends_on:
      - vaultwarden
    networks:
      - internal
    volumes:
      - ${app_data_path}/data:/data/
      - ${app_data_path}/backup:/myBackup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TIMESTAMP=true
      - DELETE_AFTER=30
      - UID=0
      - GID=1000
      - TZ=${timezone}
      - BACKUP_DIR=/myBackup
      - CRON_TIME=50 3 * * *

networks:
  internal:
    external: true
  proxy:
    external: true