services:
  vaultwarden:
    restart: always
    container_name: vaultwarden
    image: vaultwarden/server:latest
    volumes:
      - ${app_path}:/data/
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden-http.entrypoints=web
      - traefik.http.routers.vaultwarden-http.rule=Host(`${domain}`)
      - traefik.http.routers.vaultwarden-https.entrypoints=websecure
      - traefik.http.routers.vaultwarden-https.rule=Host(`${domain}`)
      - traefik.http.routers.vaultwarden-https.tls=true
    networks:
      - front
    ports:
      - 8062:80
    environment:
      - TZ=${timezone}
      - SMTP_HOST=${mail_host}
      - SMTP_FROM=${mail_username}
      - SMTP_FROM_NAME=VaultWarden
      - SMTP_SECURITY=starttls
      - SMTP_PORT=${mail_port}
      - SMTP_USERNAME=${mail_username}
      - SMTP_PASSWORD=${mail_password}
      - SMTP_TIMEOUT=30
      - SMTP_AUTH_MECHANISM="Plain"
      - LOGIN_RATELIMIT_MAX_BURST=5
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=${domain}
      - INVITATION_ORG_NAME=RivenVault
      - INVITATIONS_ALLOWED=false
      - ADMIN_TOKEN=${admin_token}
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=6
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLED=true

networks:
  front:
    external: true