---
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- MENU_VERSION=1.9.9
      - PORT_RANGE=30000:30010
      - SUBFOLDER=/
      - NGINX_PORT=80
      - WEB_APP_PORT=3000
    volumes:
      - ${app_data}/config:/config
      - ${app_data}/assets:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8484:80
    restart: unless-stopped
    networks:
      - front

networks:
  front:
    external: true
