services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL={{ app_url }}
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_DATABASE={{ mysql_database }}
      - DB_USER={{ mysql_user }}
      - DB_PASS={{ mysql_password }}
    volumes:
      - "${APP_PATH}/app_data:/config"
    ports:
      - 6875:80
    networks:
      - front
      - back
    labels:
      - traefik.enable=true
      - traefik.http.routers.bookstack-http.entrypoints=web
      - traefik.http.routers.bookstack.rule=Host(`{{ app_url }}`)
      - traefik.http.routers.bookstack-https.entrypoints=websecure
      - traefik.http.routers.bookstack.rule=Host(`{{ app_url }}`)
      - traefik.http.routers.bookstack.tls=true
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD={{ mysql_root_password }}
      - TZ={{ timezone }}
      - MYSQL_DATABASE={{ mysql_database }}
      - MYSQL_USER={{ mysql_user }}
      - MYSQL_PASSWORD={{ mysql_password }}
    volumes:
      - "${APP_PATH}/mysql_data:/config"
    networks:
      - back

networks:
  front:
    name: front
    external: true
  back:
    name: back
    external: true
