services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - app_domain=https://${app_domain}
      - APP_KEY=${app_key}
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_DATABASE=${mysql_database}
      - DB_USER=${mysql_user}
      - DB_PASS=${mysql_password}
    volumes:
      - "${app_data_path}/app_data_path:/config"
    # ports:
    #   - 6875:80
    networks:
      - proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.bookstack.entrypoints=https-external
      - traefik.http.routers.bookstack.rule=Host(`${app_domain}`)
      - traefik.http.services.bookstack.loadbalancer.server.port=80
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=$mysql_root_password
      - TZ=${timezone}
      - MYSQL_DATABASE=${mysql_database}
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_password}
    volumes:
      - "${app_data_path}/mysql_data:/config"
    networks:
      - internal

networks:
  proxy:
    name: proxy
    external: true
  internal:
    name: internal
    external: true
