services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
      - docker-proxy_lannet
    environment:
      - TZ=${timezone}
      - CF_DNS_API_TOKEN=${cf_api_token}
      - TRAEFIK_DASHBOARD_CREDENTIALS=${dashboard_credentials}
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${app_url}`)
      - traefik.http.routers.api.service=api@internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${app_data}/traefik.yml:/etc/traefik/traefik.yml
      - ${app_data}/acme.json:/acme.json
      - ${app_data}/logs:/logs
      - ${app_data}/conf.d:/etc/traefik/conf.d
    extra_hosts:
      - host.docker.internal:172.17.0.1
    security_opt:
      - no-new-privileges:true

  socket-proxy_lan:
    image: lscr.io/linuxserver/socket-proxy_lan:1.26.2
    container_name: socket-proxy_lan
    environment:
      - CONTAINERS=1
      - EVENTS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxy_lannet
    restart: always
    read_only: true
    tmpfs:
      - /run

networks:
  proxy:
    external: true
  docker-proxy_lannet:
    external: true