#accessLog = { }

[global]
checkNewVersion = false
sendAnonymousUsage = false

[log]
level = "INFO"

[api]
dashboard = true
insecure = true
debug = false


#[experimental.plugins.bouncer]
#moduleName = "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
#version = "v1.4.1"

#[experimental.influxDB2]
#address = "http://influxdb2:8086"
#token = "my-secure-token-secret"
#org = "influx-org"
#bucket = "influx-bucket"
#addEntryPointsLabels = true
#addRoutersLabels = true
#addServicesLabels = true
#pushInterval = "60s"

[accessLog]
filePath = "/logs/traefik.log"
format = "json"
bufferingSize = 0

  [accessLog.filters]
  statusCodes = [ "200-299", "400-599" ]

[accessLog.fields.headers]
defaultMode = "drop"

  [accessLog.fields.headers.names]
  User-Agent = "keep"

[entryPoints.http]
address = ":80"
  [entryPoints.http.forwardedHeaders]
  trustedIPs = [
  "103.21.244.0/22",
  "103.22.200.0/22",
  "103.31.4.0/22",
  "104.16.0.0/13",
  "104.24.0.0/14",
  "108.162.192.0/18",
  "131.0.72.0/22",
  "141.101.64.0/18",
  "162.158.0.0/15",
  "172.64.0.0/13",
  "173.245.48.0/20",
  "188.114.96.0/20",
  "190.93.240.0/20",
  "197.234.240.0/22",
  "198.41.128.0/17",
  "2400:cb00::/32",
  "2606:4700::/32",
  "2803:f800::/32",
  "2405:b500::/32",
  "2405:8100::/32",
  "2a06:98c0::/29",
  "2c0f:f248::/32"
]

[entryPoints.http.http.redirections.entryPoint]
to = "https"
scheme = "https"

[entryPoints.https]
address = ":443"

  [entryPoints.https.forwardedHeaders]
  trustedIPs = [
  "103.21.244.0/22",
  "103.22.200.0/22",
  "103.31.4.0/22",
  "104.16.0.0/13",
  "104.24.0.0/14",
  "108.162.192.0/18",
  "131.0.72.0/22",
  "141.101.64.0/18",
  "162.158.0.0/15",
  "172.64.0.0/13",
  "173.245.48.0/20",
  "188.114.96.0/20",
  "190.93.240.0/20",
  "197.234.240.0/22",
  "198.41.128.0/17",
  "2400:cb00::/32",
  "2606:4700::/32",
  "2803:f800::/32",
  "2405:b500::/32",
  "2405:8100::/32",
  "2a06:98c0::/29",
  "2c0f:f248::/32"
]

[entryPoints.https.http]
middlewares = [ "security-headers@file", "rate-limit@file" ]

[ping]
entryPoint = "websecure"

[serversTransport]
insecureSkipVerify = true

[providers]
providersThrottleDuration = "2s"
[providers.file]
watch = true
directory= "/etc/traefik/conf.d/"

[providers.docker]
watch = true
network = "proxy"
endpoint = "tcp://socket-proxy:2375"
defaultRule = 'Host(`{{ index .Labels "com.docker.compose.service"}}.rvlab.xyz`)'
exposedByDefault = false