# accessLog = { }

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: ERROR

api:
  dashboard: true
  insecure: true
  debug: false

# experimental.influxDB2:
#   address: "http://influxdb2:8086"
#   token: "my-secure-token-secret"
#   org: "influx-org"
#   bucket: "influx-bucket"
#   addEntryPointsLabels: true
#   addRoutersLabels: true
#   addServicesLabels: true
#   pushInterval: "60s"

# Configuring Multiple Filters
accessLog:
  filePath: "/logs/traefik.log"
  format: json
  filters:
    statusCodes:
      - "200-299" # log successful http requests
      - "400-599" # log failed http requests
    #retryAttempts: true
    #minDuration: "10ms"
  # collect logs as in-memory buffer before writing into log file
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop # drop all headers per default
      names:
          User-Agent: keep # log user agent strings

# The setting below is to allow insecure backend connections.
serverTransport:
  insecureSkipVerify: true

# Traefik entrypoints (network ports) configuration
entryPoints:
### INTERNAL
  # Redirect everything from HTTP to HTTPS
  http-internal:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https-internal:
    address: :443
    forwardedHeaders:
    http:
      tls:
        options: default
        certResolver: cloudflare
        domains:
          - main: fqdn1
            sans:
              - '*.fqdn1'
          - main : fqdn2
            sans:
              - '*.fqdn2'
      middlewares:
        - security-headers@file # reference to a dynamic middleware for setting http security headers per default
        - rate-limit@file # reference to a dynamic middleware for enabling rate limiting per default
        #- crowdsec@file # reference to a dynamic middleware for enabling crowdsec bouncer

### EXTERNAL
  # Redirect everything from HTTP to HTTPS
  http-external:
    address: :81
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https-external:
    address: :444
    forwardedHeaders:
    http:
      tls:
        options: default
        certResolver: cloudflare
        domains:
          - main: fqdn1
            sans:
              - '*.fqdn1'
          - main : fqdn2
            sans:
              - '*.fqdn2'
      middlewares:
        - security-headers@file # reference to a dynamic middleware for setting http security headers per default
        - rate-limit@file # reference to a dynamic middleware for enabling rate limiting per default
        #- crowdsec@file # reference to a dynamic middleware for enabling crowdsec bouncer

providers:
  providersThrottleDuration: 2s
  file:
    watch: true
    directory: /etc/traefik/conf.d/

  docker:
    watch: true
    network: proxy
    endpoint: "tcp://socket-proxy:2375"
    # defaultRule: 'Host(`{{ index .Labels "com.docker.compose.service"}}.fqdn1`)'
    exposedByDefault: false

certificatesResolvers:
  cloudflare:
    acme:
      email: "example@example.com"
      storage: "acme.json"
      # caServer: "https://acme-v02.api.letsencrypt.org/directory" # production (default)
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory" # staging
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"