services:
  grafana:
    image: grafana/grafana-oss:main
    container_name: grafana
    restart: unless-stopped
    user: "1000:1000"
    environment:
     - GF_SERVER_ROOT_URL=https://${app_url}
     - GF_PLUGINS_PREINSTALL=grafana-clock-panel
     - GF_DEFAULT_INSTANCE_NAME=grafana
     - GF_LOG_LEVEL=error
    ports:
     - '3000:3000'
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`${app_url}`)
      - traefik.http.routers.grafana.entrypoints=https
      - traefik.http.routers.grafana.tls=true
    volumes:
     - ${app_data}/data:/var/lib/grafana
    networks:
     - proxy
networks:
  proxy:
    external: true