services:
  grafana:
    image: grafana/grafana-oss:main
    container_name: grafana
    restart: unless-stopped
    user: "1000:1000"
    environment:
     - GF_SERVER_ROOT_URL=https://${domain}
     - GF_PLUGINS_PREINSTALL=grafana-clock-panel
     - GF_DEFAULT_INSTANCE_NAME=grafana
    ports:
     - '3000:3000'
    labels:
     - traefik.enable=true
     - traefik.http.routers.grafana-http.entrypoints=web
     - traefik.http.routers.grafana-http.rule=Host(`${domain}`)
     - traefik.http.routers.grafana-https.entrypoints=websecure
     - traefik.http.routers.grafana-https.rule=Host(`${domain}`)
     - traefik.http.routers.grafana-https.tls=true
    volumes:
     - ${app_data}/data:/var/lib/grafana
    networks:
     - front
networks:
  front:
    external: true