---
services:
  passbolt-db:
    image: mariadb:11.5
    container_name: passbolt-db
    hostname: passbolt-db
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
    volumes:
      - ${app_data_path}/mysql:/var/lib/mysql
    networks:
      - internal

  passbolt:
    image: passbolt/passbolt:latest-ce-non-root
    container_name: passbolt
    hostname: passbolt
    restart: always
    depends_on:
      - passbolt-db
    environment:
      APP_FULL_BASE_URL: https://${app_domain}
      DATASOURCES_DEFAULT_HOST: passbolt-db
      DATASOURCES_DEFAULT_USERNAME: ${mysql_user}
      DATASOURCES_DEFAULT_PASSWORD: ${mysql_password}
      DATASOURCES_DEFAULT_DATABASE: ${mysql_database}
      EMAIL_DEFAULT_FROM_NAME: ${mail_username}
      EMAIL_DEFAULT_FROM: ${mail_username}
      EMAIL_TRANSPORT_DEFAULT_HOST: ${mail_host}
      EMAIL_TRANSPORT_DEFAULT_PORT: ${mail_port}
      EMAIL_TRANSPORT_DEFAULT_USERNAME: ${mail_username}
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: ${mail_password}
      EMAIL_TRANSPORT_DEFAULT_TLS: true
    volumes:
      - ${app_data_path}/gpg:/etc/passbolt/gpg
      - ${app_data_path}/jwt:/etc/passbolt/jwt
    command: ["/usr/bin/wait-for.sh", "-t", "0", "passbolt-db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      # - 8543:8080
      # - 8432:4433
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.passbolt.entrypoints=https-internal
      - traefik.http.routers.passbolt.rule=Host(`${app_domain}`)
      - traefik.http.services.passbolt.loadbalancer.server.port=8080

networks:
  proxy:
    external: true
  internal:
    external: true