services:
  vikunja:
    image: vikunja/vikunja
    container_name: todo
    environment:
      VIKUNJA_SERVICE_PUBLICURL: ${domain}
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${mysql_password}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: ${mysql_user}
      VIKUNJA_DATABASE_DATABASE: ${mysql_database}
      VIKUNJA_SERVICE_JWTSECRET: ${jwt_secret}
      VIKUNJA_SERVICE_ENABLEREGISTRATION: 0
      VIKUNJA_SERVICE_ENABLETASKATTACHMENTS: 1
      VIKUNJA_MAILER_ENABLED: 0
      VIKUNJA_MAILER_FORCESSL: 1
      VIKUNJA_MAILER_HOST: ${mail_host}
      VIKUNJA_MAILER_PORT: ${mail_port}
      VIKUNJA_MAILER_USERNAME: ${mail_username}
      VIKUNJA_MAILER_PASSWORD: ${mail_password}
      VIKUNJA_ALLOW_ICON_CHANGES: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.vikunja.entrypoints=websecure
      - traefik.http.routers.vikunja.tls=true
      - traefik.http.routers.vikunja.rule=Host(`${domain}`)
      - traefik.http.routers.vikunja.service=vikunja
    networks:
      - front
      - back
    volumes:
      - ${app_path}/files:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
      MYSQL_DATABASE: ${mysql_database}
    volumes:
      - ${app_path}/db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - back
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s

networks:
  front:
    name: front
    external: true
  back:
    name: front
    external: true