---
services:
  ocis:
    image: owncloud/ocis:latest
    container_name: owncloud-ocis
    restart: always
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: https://${app_url}
      OCIS_LOG_LEVEL: warn
      OCIS_LOG_COLOR: "false"
      PROXY_TLS: "false"
      OCIS_INSECURE: "true"
      PROXY_ENABLE_BASIC_AUTH: "false"
      IDM_ADMIN_PASSWORD: ${admin_password}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.owncloud.rule=Host(`${app_url}`)
      - traefik.http.routers.owncloud.entrypoints=https
      - traefik.http.routers.owncloud.tls=true
    volumes:
      - ${app_data}/cfg:/etc/ocis
      - ${app_data}/app:/var/lib/ocis

networks:
  proxy:
    external: true