---
services:
  ocis:
    image: owncloud/ocis:latest
    container_name: owncloud-ocis
    restart: always
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: https://${app_domain}
      OCIS_LOG_LEVEL: error
      OCIS_LOG_PRETTY: true
      OCIS_LOG_COLOR: true
      PROXY_TLS: false
      OCIS_INSECURE: true
      PROXY_ENABLE_BASIC_AUTH: false
      IDM_ADMIN_PASSWORD: ${admin_password}
      STORAGE_USERS_DATA_GATEWAY_URL: http://ocis:9200/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.ocis.entrypoints=https-external
      - traefik.http.routers.ocis.rule=Host(`${app_domain}`)
      - traefik.http.services.ocis.loadbalancer.server.port=9200
      # - traefik.http.middlewares.limit-ocis.buffering.maxRequestBodyBytes=50000000
      # - traefik.http.middlewares.limit-ocis.buffering.maxResponseBodyBytes=50000000
      # - traefik.http.middlewares.limit-ocis.buffering.memRequestBodyBytes=50000000
      # - traefik.http.middlewares.limit-ocis.buffering.memResponseBodyBytes=50000000
      # Disallow listing version details via /status.php endpoint
      - traefik.http.routers.ocis-version-disclosure.rule=Host(`${app_domain}`) && Path(`/status.php`)
      - traefik.http.routers.ocis-version-disclosure.middlewares=restriction@file
      - traefik.http.routers.ocis-version-disclosure.entrypoints=https-external
    volumes:
      - ${app_data_path}/cfg:/etc/ocis
      - ${app_data_path}/app:/var/lib/ocis
    logging:
      driver: "local"
networks:
  proxy:
    external: true