---
services:
  ocis:
    image: owncloud/ocis:latest
    container_name: owncloud-ocis
    restart: always
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    #ports:
    #  - "9200:9200"
    environment:
      OCIS_URL: https://${app_url}
      OCIS_LOG_LEVEL: debug
      OCIS_LOG_COLOR: "false"
      proxy_TLS: "false"
      OCIS_INSECURE: "true"
      proxy_ENABLE_BASIC_AUTH: "false"
      IDM_ADMIN_PASSWORD: ${admin_password}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      # - traefik.http.routers.owncloud.entrypoints=https-internal
      - traefik.http.routers.owncloud.rule=Host(`${app_url}`)
      - traefik.http.services.owncloud.loadbalancer.server.port=9200
      # - traefik.http.middlewares.limit-owncloud.buffering.maxRequestBodyBytes=50000000
      # - traefik.http.middlewares.limit-owncloud.buffering.maxResponseBodyBytes=50000000
      # - traefik.http.middlewares.limit-owncloud.buffering.memRequestBodyBytes=50000000
      # - traefik.http.middlewares.limit-owncloud.buffering.memResponseBodyBytes=50000000
      # - traefik.http.routers.owncloud.middlewares=limit-owncloud
      # # disallow listing version details via /status.php endpoint
      # - traefik.http.routers.owncloud-version-disclosure.rule=Host(`${app_url}`) && Path(`/status.php`)
      # - traefik.http.routers.owncloud-version-disclosure.middlewares=restriction@file
    volumes:
      - ${app_data}/cfg:/etc/ocis
      - ${app_data}/app:/var/lib/ocis

networks:
  proxy:
    external: true