---
services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost-cms
    restart: always
    # ports:
    #   - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ${ghost_db_user}
      database__connection__password: ${ghost_db_password}
      database__connection__database: ${ghost_db}
      url: https://${app_domain}
      NODE_ENV: production
    volumes:
      - ${app_data_path}/public_html:/var/lib/ghost/content
      - ${app_data_path}/config/config.production.json:/var/lib/ghost/config.production.json
    networks:
      - proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost-cms.entrypoints=https-internal
      - traefik.http.routers.ghost-cms.rule=Host(`${app_domain}`)
      - traefik.http.services.ghost-cms.loadbalancer.server.port=2368

  ghost-db:
    image: mysql:8.0
    container_name: ghost-cms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ghost_db_root_password}
    volumes:
      - ${app_data_path}/mysql:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    external: true
  proxy:
    external: true