[http]
[http.routers]

[http.routers.pfsense]
rule = "Host(`sub.example.com`)"
service = "fw"
entryPoints = ["https"]
tls = true

[http.routers.prx-cloud]
rule = "Host(`sub2.example.com`)"
service = "prx-cloud"
entryPoints = ["https"]
tls = true

####################################################################

[http.services]
[http.services.fw.loadBalancer]
[[http.services.fw.loadBalancer.servers]]
url = "https://10.0.0.1:9111"

[http.services.prx-cloud.loadBalancer]
[[http.services.prx-cloud.loadBalancer.servers]]
url = "https://10.0.0.2:8006"