[http.middlewares]
[http.middlewares.https-redirect.redirectScheme]
  scheme = "https"
  permanent = true
[http.middlewares.restriction.ipAllowList]
sourceRange = [
  "127.0.0.1/32",
  "10.0.0.0/8",
  "172.16.0.0/12",
  "192.168.0.0/16"
]

[http.middlewares.security-headers.headers]
hostsProxyHeaders = [ "X-Forwarded-Host" ]
contentTypeNosniff = true
customFrameOptionsValue = "SAMEORIGIN"
browserXssFilter = false
referrerPolicy = "strict-origin-when-cross-origin"
forceSTSHeader = true
stsIncludeSubdomains = true
stsSeconds = 63_072_000
stsPreload = true

  [http.middlewares.security-headers.headers.customResponseHeaders]
  Server = ""
  X-Powered-By = ""
  X-Forwarded-Proto = "https"

  [http.middlewares.security-headers.headers.sslProxyHeaders]
  X-Forwarded-Proto = "https"

  [http.middlewares.security-headers.headers.customRequestHeaders]
  X-Forwarded-Proto = "https"

[http.middlewares.rate-limit.rateLimit]
average = 100
period = 1
burst = 100

[http.middlewares.basic-auth.basicAuth]
users = "admin:$2y$05$PtkRamYTn23eF/FBOAESr.ZOaQihD9SiwBNlwv5BDu6t/0IbOCnfS"

[tls.options.default]
minVersion = "VersionTLS12"
cipherSuites = [
  "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
  "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
]
