services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${app_path}/traefik.toml:/etc/traefik/traefik.toml
      - ${app_path}/acme.json:/acme.json
      - ${app_path}/conf.d:/etc/traefik/conf.d
    restart: always

networks:
  front:
    external: true