services:
  webdb:
    image: webdb/app
    restart: always
    container_name: webdb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${app_data}/.ssh:/root/.ssh:ro"
      - "${app_data}/.webdb:/usr/src/app/static/version"
    ports:
      - "127.0.0.1:22071:22071"
    labels:
      - traefik.enable=true
      - traefik.http.routers.webdb.rule=Host(`${app_url}`)
    networks:
      - proxy
      - internal

  maria:
    image: mariadb
    container_name: webdb_maria
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${maria_root_password}
    networks:
      - internal

  postgre:
    image: postgres
    container_name: webdb_postgress
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${postgress_root_password}
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    external: true