---
services:
  app:
    image: odoo:19
    container_name: odoo19
    depends_on:
      - db
    restart: always
    #ports:
    #  - "8069:8069"
    #  - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ${app_data_path}/config:/etc/odoo
      - ${app_data_path}/addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    networks:
      - internal
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.it-tools.entrypoints=https-internal
      - traefik.http.routers.it-tools.rule=Host(`${app_domain}`)
      - traefik.http.services.it-tools.loadbalancer.server.port=8069
  db:
    image: postgres:17
    container_name: odoo19_db
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ${app_data_path}/database:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    networks:
      - proxy
      - internal

volumes:
  odoo-web-data:
secrets:
  postgresql_password:
    file: ${app_data_path}/odoo_pg_pass

networks:
  internal:
    external: true
  proxy:
    external: true