services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.8
    container_name: crowdsec
    restart: unless-stopped
    ports:
      - 127.0.0.1:9876:8080 # http api for local fw bouncers
      - 127.0.0.1:6060:6060 # metrics endpoint for prometheus
    expose:
      - 8080 # http api for bouncers
      - 6060 # metrics endpoint for prometheus
      - 7422 # appsec waf endpoint
    volumes:
      # crowdsec container data
      - ${app_data}/data:/var/lib/crowdsec/data
      - ${app_data}/etc:/etc/crowdsec
      # log bind mounts into crowdsec
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog:ro
      - ${traefik_log_path}:/var/log/traefik:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.crowdsec.entrypoints=https-internal
      - traefik.http.routers.crowdsec.rule=Host(`${app_url}`)
    environment:
      - GID=1000
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/sshd crowdsecurity/linux crowdsecurity/appsec-crs crowdsecurity/appsec-generic-rules crowdsecurity/appsec-virtual-patching
      - CUSTOM_HOSTNAME=crowdsec
    # security_opt:
    #  - no-new-privileges=true      
    networks:
     - proxy

networks:
 proxy:
   external: true